name: CI/CD - Build & Push Docker image

on:
  push:
    branches:
      - main
    tags:
      - v*.*.*
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image (main branch)
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            tzachipinhas/budget_app:latest
            tzachipinhas/budget_app:${{ github.sha }}

      - name: Build and push Docker image (tagged release)
        if: startsWith(github.ref, 'refs/tags/')
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            tzachipinhas/budget_app:latest
            tzachipinhas/budget_app:${{ github.sha }}
            tzachipinhas/budget_app:${{ github.ref_name }}
